
#
# This LookML file was generated by AtScale on 2023-08-30T16:58:39.292690Z
#
# AtScale engine version: 2023.2.0.12240
# AtScale DesignCenter version: 2023.2.0.20954
# AtScale version: 2023.2.0.6157
# Organization: default
# Project: 10TB - GBQ-AZ

connection: "atscale_az"
label: "10TB - GBQ-AZ"


include: "/views/10TB_-_GBQ-AZ/10TB_-_GBQ-AZ.view.lkml"


explore: 10TB___GBQ_AZ {
  label: "10TB - GBQ-AZ"
}

