
#
# This LookML file was generated by AtScale on 2023-08-30T15:47:32.079492Z
#
# AtScale engine version: 2023.2.0.12240
# AtScale DesignCenter version: 2023.2.0.20954
# AtScale version: 2023.2.0.6157
# Organization: default
# Project: 10TB - GBQ

connection: "atscale_az"
label: "10TB - GBQ"


include: "/views/10TB_-_GBQ/10TB_-_GBQ.view.lkml"


explore: 10TB___GBQ {
  label: "10TB - GBQ"
}

