
#
# This LookML file was generated by AtScale on 2023-03-07T22:07:09.639508Z
#
# AtScale engine version: 2022.4.0.11920
# AtScale DesignCenter version: 2022.4.0.20433
# AtScale version: 2022.4.0.5571
# Organization: default
# Project: Albert Test Model

connection: "atscale_az"
label: "Albert Test Model"


include: "/views/Albert_Test_Model/Internet_Sales_Cube.view.lkml"

include: "/views/Albert_Test_Model/Finance_View.view.lkml"


explore: Internet_Sales_Cube {
  label: "Internet Sales Cube"
}

explore: Finance_View {
  label: "Finance View"
}

