
#
# This LookML file was generated by AtScale on 2023-02-16T22:01:20.978753Z
#
# AtScale engine version: 2022.3.1.11773
# AtScale DesignCenter version: 2022.3.1.19909
# AtScale version: 2022.3.1.5201
# Organization: default
# Project: Albert Test Model

connection: "atscale_az"
label: "Albert Test Model"


include: "/views/Albert_Test_Model/Internet_Sales_Cube.view.lkml"


explore: Internet_Sales_Cube {
  label: "Internet Sales Cube"
}

