
#
# This LookML file was generated by AtScale on 2023-05-02T06:51:40.419764Z
#
# AtScale engine version: 2022.4.0.11920
# AtScale DesignCenter version: 2022.4.0.20433
# AtScale version: 2022.4.0.5571
# Organization: default
# Project: az test

connection: "atscale_az"
label: "az test"


include: "/views/az_test/az_test.view.lkml"


explore: az_test {
  label: "az test"
}

