
#
# This LookML file was generated by AtScale on 2022-09-30T04:29:18.615734Z
#
# AtScale engine version: 2022.2.0.11610
# AtScale DesignCenter version: 2022.2.0.19507
# AtScale version: 2022.2.0.4819
# Organization: default
# Project: Sales Insights

connection: "atscale_az"
label: "Sales Insights"


include: "/views/Sales_Insights/Internet_Sales_Cube.view.lkml"


explore: Internet_Sales_Cube {
  label: "Internet Sales Cube"
}

