
#
# This LookML file was generated by AtScale on 2023-02-21T22:47:36.705579Z
#
# AtScale engine version: 2022.3.1.11773
# AtScale DesignCenter version: 2022.3.1.19909
# AtScale version: 2022.3.1.5201
# Organization: default
# Project: Sales Insights AZ

connection: "atscale_az"
label: "Sales Insights AZ"


include: "/views/Sales_Insights_AZ/Internet_Sales_Cube_AZ.view.lkml"


explore: Internet_Sales_Cube_AZ {
  label: "Internet Sales Cube AZ"
}

