
#
# This LookML file was generated by AtScale on 2023-02-21T22:32:23.645801Z
#
# AtScale engine version: 2022.3.1.11773
# AtScale DesignCenter version: 2022.3.1.19909
# AtScale version: 2022.3.1.5201
# Organization: default
# Project: Sales Insights

connection: "atscale_az"
label: "Sales Insights"


include: "/views/Sales_Insights/Internet_Sales_Cube.view.lkml"


explore: Internet_Sales_Cube {
  label: "Internet Sales Cube"
}

